import type { Metadata } from "next";
import "../styles/globals.css";
import { NavBar } from "@/components/layout/NavBar";
import { loraDisplay } from "@/styles/fonts";
import { NavBarLinks } from "@/constants/Navigation";
import { Analytics } from "@vercel/analytics/next";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${loraDisplay.className} text-[#3f3f3f]`}>
        <NavBar links={NavBarLinks} />
        {children}
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
