import type { Metadata } from "next";
import { Playfair_Display, Plus_Jakarta_Sans, Lora } from "next/font/google";
import "../styles/globals.css";
import { NavBar } from "@/components/layout/NavBar";

export const plusJakartaDisplay = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const loraDisplay = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navBarLinks = [
  { name: "Home", href: "/" },
  { name: "Menu", href: "/menu" },
  { name: "Reviews", href: "/reviews" },
  { name: "Contact", href: "/contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${loraDisplay.className} text-[#3f3f3f]`}>
        <NavBar links={navBarLinks} />
        {children}
      </body>
    </html>
  );
}
