import type { Metadata } from "next";
import "../styles/globals.css";
import { NavBar } from "@/components/layout/NavBar";
import { loraDisplay } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navBarLinks = [
  { name: "Home", href: "/" },
  { name: "Menu", href: "/menu" },
  { name: "Reviews", href: "/reviews" },
  { name: "Contact", href: "/contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${loraDisplay.className} text-[#3f3f3f]`}>
        <NavBar links={navBarLinks} />
        {children}
      </body>
    </html>
  );
}
